# Generated by Django 6.1 on 2026-08-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_heatmappin_sosalert_trustedcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustedcontact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
